### ISSUE TITLE
Boundary flux calculation is incorrect for non-absorb BCs

### ISSUE THREAD

**Issue by kltrbrds** [ammarhakim/gkylzero#102]
- Currently the boundary flux calculation is done by performing a surface update on the skin cell, a zeroed ghost cell, and blank dummy cell. This gives the surface term at the skin/ghost interface, and a zero flux at the ghost/dummy interface.
- For the absorbing wall BC this is correct as the only contribution to the surface term is made by the skin cell distribution. For other BCs, there is a distribution in the ghost cell which should contribute to the skin/ghost surface update as well.
- However, doing an update with the ghost cell distribution supplied by the BC causes there to be an additional unwanted surface contribution from the ghost/dummy interface.
- Some means of separating the left and right surface term updates is therefore required.

**Comment by JunoRavin** [comment]
Issue fixed with PR: 2523a14
