### ISSUE TITLE
Throw error/failure when unit test produces a NaN

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#153]
Presently our gkyl_compare function to compare to numbers in unit tests returns true (1) if one of the numbers is a NaN. This is problematic because it leads us to believe something is working when in fact it isn't.

**Comment by ammarhakim** [comment]
This can not be done easily. We use the fast_math option and this disables nan checking. As such I am marking this "wont do". One possibility is to have a debug build in which we do not use fast_math option. But we will look into this later.
