### ISSUE TITLE
Remove p=2 tensor basis from LBO kernels

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkylzero#168]
Seems there are unused p=2 tensor basis kernels in LBO, left over from previous experimental stuff. These should be deleted. Large unused kernels cause long build times, specially with GPUs.

**Comment by JunoRavin** [comment]
There are currently no tensor Vlasov kernels so I am closing this issue as completed (at least at some point this request was filled). There are tensor PKPM kernels but these are desired and should be there in the repo.

**Comment by manauref** [comment]
I removed all remaining p=2 GK kernels in the nonuniformv branch
