### ISSUE TITLE
Compiling on M1 Mac

### ISSUE THREAD

**Issue by Maxwell-Rosen** [ammarhakim/gkylzero#172]
The ARM architecture of the M1 Mac has a problem with how Gkeyll handles denormalized floating point numbers. It has something to do with Clang and gives this error.

`apps/vlasov.c:15:3: error: call to undeclared function 'disable_denorm_float'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`

The solution to resolving this is to comment out `ARCH_FLAGS=-march=native` in `Makefile` and `configure`. Furthermore, in `zero/gkyl_dflt.h`, one must comment out the following lines

`-# include <xmmintrin.h>
-#include <fenv.h>`

Plus everything inside the if block starting with `-#if defined(__GNUC__) || defined(__GNUG__)`

**Comment by JunoRavin** [comment]
This issue was fixed with this commit: https://github.com/ammarhakim/gkylzero/commit/95f605210a5a6aa5304d7988d9b4081abfdabb2e
