### ISSUE TITLE
gkyl_range_iter doesn't work as expected with multi-dim ranges that have a lower[i]>upper[i] when i>0.

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#186]
the functions gkyl_range_iter_init and gkyl_range_iter_next (specifically, the former) do not work on a multidimensional range where range.lower[i] > range.upper[i] for i>0. When this is the case a seg fault appears.

You can test this with the unit test added in PR #185, ```test_range_iter_init_next``` in unit/ctest_range.c, by changing line 88
```
  int lower2d[] = {1,1}, upper2d[] = {17,6};
``` 
to
```
  int lower2d[] = {1,7}, upper2d[] = {17,6};
``` 

This is a problem in parallel sims where an MPI process may create a range with lower>upper as a way to force that process to not perform an operation in that range.

**Comment by ammarhakim** [comment]
PR 185 fixes this issue.
