### ISSUE TITLE
gk app: geo files don't have the sim name prefixed

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#243]
The GK app is writing a bunch of geometry/field related files without the filename prefix

allxyz.gkyl
b_i.gkyl
bmag.gkyl
bmag_inv.gkyl
...

These should have the name of the sim as a prefix, like all our other output data.

**Comment by JunoRavin** [comment]
This issue was solved by @akashukla in this commit https://github.com/ammarhakim/gkylzero/commit/3b35faf3a876805be02a4af1ad7de67592c08f7f

and now geometry is written to file with a matching name.
