### ISSUE TITLE
Restarts in g0 apps

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#246]
We need restarts to do production science and debug longer sims.

**Comment by akashukla** [comment]
Yes this is important. Perlmutter for example only allows 24 hour jobs, so restarts are necessary.

**Comment by JunoRavin** [comment]
This functionality was added with PR https://github.com/ammarhakim/gkylzero/pull/319 into the gk-g0-app branch (https://github.com/ammarhakim/gkylzero/tree/gk-g0-app). The rest of the code will gain restart functionality when this branch is merged.
