### ISSUE TITLE
Memory leak in RHS vector creation using superLU in CPU simulations

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#254]
When we use superLU for simulations on the CPU, we must construct the RHS vector b to solve Ax = b for operations such as Poisson solves in, e.g., a gyrokinetic simulation.

Right now this is done in this line wrapping a call to superLU: https://github.com/ammarhakim/gkylzero/blob/main/zero/superlu_ops.c#L198

this function calls out to this superLU method: https://github.com/ammarhakim/gkylzero/blob/main/zero/superlu_ops.c#L205

This call does a malloc every time it's called, but we only call a corresponding free once at the end of a simulation. In effect, the way we are currently using superLU, we do not have complete control over the SuperMatrix data structure that superLU utilizes for linear solves (because the SuperMatrix object has a data structure "Store" which is malloced every time you call the routines to create the matrix). 

We could free this memory after we're done with it, but that seems not ideal because it would mean we are allocating and de-allocating memory in the "inner" loop of time-stepping within a simulation.

This issue is not present on GPUs because the equivalent routines to create the RHS vector for use in cuSolvers give us direct access to just filling entries of the matrix. Thus we create the memory once and then change the entries of the matrix at every timestep with the new values of b.

**Comment by manauref** [comment]
Addressed in 10f9a212b4760c43f5d9f7ca8ea36b3ad733cc30

**Comment by JunoRavin** [comment]
This issue was solved by @manauref in this commit https://github.com/ammarhakim/gkylzero/commit/10f9a212b4760c43f5d9f7ca8ea36b3ad733cc30

It turns out we can create and destroy this memory inside the time loop without a significant performance hit, so now that is our approach to let SuperLU allocate this memory and then we ourselves delete it when we are finished with it every linear solve.
