### ISSUE TITLE
Update calc_bmag header file

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#255]
the file

```
zero/gkyl_calc_bmag.h
```

needs to be updated with accurate descriptions of the functions in this object, and its arguments, so we can use and/or modify it.

**Comment by ammarhakim** [comment]
We really have to ensure that the comment documenting the function prototype are correct and accurate. It does not take time to make sure you do this right the first time. The longer you wait the harder it gets. We have now nearly 80K C code. It won't be easy to detect all these errors and fix. Please do this as one codes.

**Comment by manauref** [comment]
addressed in commit 1434a7ac7edb8835c5ec0edf97c3151cdd16ce8e
