### ISSUE TITLE
Save timestamp in .gkyl output files

### ISSUE THREAD

**Issue by jRoeltgen** [ammarhakim/gkylzero#258]
It's difficult to tell precisely what the simulation time is for a .gkyl file that is output from the gkyrokinetic app as the time is not recorded within the file itself. It would be useful to save that time within the .gkyl file.

**Comment by JunoRavin** [comment]
This issue has been addressed by this PR: https://github.com/ammarhakim/gkylzero/pull/319

in the gk-g0-app branch (https://github.com/ammarhakim/gkylzero/tree/gk-g0-app). Now the time is one of the inputs to the gkyl_array_meta struct that is passed to all write commands (along with frame number, basis type, and polynomial order).
