### ISSUE TITLE
Implement T_parallel and T_perp into prim_moms

### ISSUE THREAD

**Issue by Maxwell-Rosen** [ammarhakim/gkylzero#265]
I'm working on branch gk-g0-app and it would be tremendously helpful if the diagnostics for T_parallel and T_perp were included into the prim_moms output.

**Comment by manauref** [comment]
@JunoRavin you might be better suited to address this, because I have no clue how diagnostics work in the g0 app

**Comment by JunoRavin** [comment]
This functionality is now implemented as of https://github.com/ammarhakim/gkylzero/pull/350

One can request either the "MaxwellianMoments" which return (n, u_par, T/m)
or one can request the "BiMaxwellianMoments" which return (n, u_par, T_par/m, T_perp/m)

in the same way one requests "M0, M1, M2,..."
