### ISSUE TITLE
Completely refactor regression tests

### ISSUE THREAD

**Issue by JonathanGorard** [ammarhakim/gkylzero#272]
I propose that a more-or-less total refactor of the regression tests is necessary, in order to achieve a few things:

1. To (re)introduce consistent support for memory tracing, MPI and CUDA across all test cases.
2. To reduce needless code duplication (e.g. with the same mathematical and physical constants being repeatedly defined for ions, electrons, fields, etc.) that make regression tests more difficult to modify.
3. To enforce some consistency in naming/commenting/structure conventions, as per Issue #270.
4. Relatedly, to be able to have a consistent regression template (or perhaps a couple) for each g0 app, so as to ease the creation of new tests, without the need to copy-and-paste existing test cases.
5. As per Issue #188, to remove all files in the /regression directory that are really simulation code (right now my very coarse criterion is "Does it take longer than a minute or two to run on my laptop?") and perhaps move the to the input file repository.

I'm going to start with the moment app (simply because I suspect that this is the least likely to cause merge conflicts with other stuff that people are doing) and work my way outwards from there.

**Comment by manauref** [comment]
@JonathanGorard regarding 5, though it's true that we are currently using /regression as a dumping ground for production input files, it also true (I believe) that almost every input file tests something different. In this sense, if true, every input file is a valid regression test, or can be made into one, by for example, reducing its run time, num_frames and resolution so it runs in seconds.

Perhaps MOST CRITICALLY, in my opinion, is the fact that we don't have a way to quickly check if results are correct. We currently have to do it by hand using pgkyl. This should be addressed ASAP (I can show you what we had in gkyl/g2 if it'll help)

**Comment by JonathanGorard** [comment]
@manauref Thanks very much for this! With regards to your second point in relation to result correctness, I currently have a very crude solution implemented within the auto-regression script I've written, wherein the contents of the *.gkyl file from the latest run are simply directly compared against the contents for the previous run, and it gets flagged within the dashboard if they differ. I can show this in our meeting on Wednesday. But I'll try to implement something more sophisticated very soon.

With regards to your first point, that's a very interesting claim. I'd be curious to get other opinions regarding whether any of the files in /regression really need to be (re)moved, or if we can just modify their parameters a little so that they become tractable to run in an automated fashion.
