### ISSUE TITLE
Implement both static and adaptive mesh refinement (AMR)

### ISSUE THREAD

**Issue by JonathanGorard** [ammarhakim/gkylzero#280]
For any simulations of physical processes involving multiple characteristic length scales (for instance, multi-fluid simulations that involve strong shock waves), it is often beneficial or even necessary to use a computational mesh with a heterogeneous resolution. If the qualitative behavior of the solution is known a priori (as, for instance, in simulations of a steady-state shock profile around a moving object), then static mesh refinement can be used to great effect in such cases. If the qualitative behavior cannot be accurately estimated ahead of time, or is fundamentally dynamic in nature (as, for instance, in simulations involving eddies, vortices and fluid instabilities), then full adaptive mesh refinement may be required instead.

Eventually, the objective is to implement full space-time adaptive mesh refinement into at least the Gkeyll moment app (with potential extensions to the Vlasov-Maxwell and gyrokinetics apps, if this is deemed useful - the benefits are less clear in these cases), using appropriate finite-volume modifications of the [Berger-Oliger algorithm for block-structured/hierarchical AMR](https://www.sciencedirect.com/science/article/pii/0021999184900731). Since this is a fairly complex task, the first objective will be to build an API for handling hierarchical space-time _static_ mesh refinement, by extending and generalizing the prototype multi-block infrastructure already implemented in rt_euler_multiblock.c.

In order to build such an API, we must first produce robust and general functions for constructing the relevant block topologies, applying the relevant inter-block boundary conditions, and synchronizing the relevant blocks within the hierarchy (all in general numbers of dimensions, and with general block topologies, as opposed to the currently hard-coded 2D implementation in rt_euler_multiblock.c). We must then implement appropriate modifications to the multi-block updaters and multi-block time-step calculations to ensure that finer mesh regions can be recursively updated at the correct rates without introducing either numerical diffusion in the coarser mesh (due to artificially dropping the CFL coefficient) or numerical instabilities in the finer mesh (due to artificially increasing it), with appropriate synchronization with coarser mesh regions. We must also produce modifications of the existing block projection functions for projecting quantities correctly from coarse-to-fine and fine-to-coarse meshes. We shall focus on getting the implementation working in serial first, and then worry about extending to MPI and CUDA.

We shall also focus initially on getting the static mesh refinement algorithm functioning for Cartesian meshes only, before extending it to the more general curvilinear coordinate systems supported by Gkeyll (which will require geometry information to be passed from skin to ghost cells in a manner that facilitates the computation of the relevant Jacobians when applying inter-block boundary conditions). In the first instance, we shall also produce an implementation that does not modify the form of the finite-volume update formula at coarse-fine mesh boundaries. This is strictly incorrect, since such a scheme is formally non-conservative at mesh boundaries (which can, for instance, introduce spurious waves into the solution around boundaries), but it will nevertheless be useful for prototyping. We will then be in a position to quantify these conservation errors precisely, in order to ascertain whether modifications to the finite-volume update scheme may be necessary (and, if so, in which cases).

**Comment by liangwang0734** [comment]
Hi Jonathan,

It's exiting to learn your plan of AMR and SMR. And I support the idea that
at this stage we do not need enforce the flux conservation. My colleague in
another code had some success like this in MHD code, particularly with
first order methods.

I also would like to back your idea about static mesh refinement: almost
all of our space applications do not really need adaptive refinement.

At some point, perhaps we also need to think about storage format solutions
for 3d data: do we need to employ some existing AMR format, or is it
beneficial to develop our own protocol and readers for cork, etc.
