### ISSUE TITLE
Allow use of eval_on_node for advection velocity in vlasov

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkylzero#37]
For some problems it will be valuable to have a nodal velocity field (to ensure continuity). For this, pass a flag to the vlasov_advection struct that will instead make the app use the eval_on_node updater instead.

**Comment by JunoRavin** [comment]
Now proj_on_basis takes an input struct which allows one to initialize the velocity field (or any projected function) with Gauss-Lobatto quadrature of a specified order. See https://github.com/ammarhakim/gkylzero/commit/3bcc195615e722a13985632250b46aabdbeaa064
