### ISSUE TITLE
Steady state source in vm_species_source doesn't work with multiple GPUs

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#371]
I haven't tested it but just reading the code in `apps/vm_species_source` I get the sense that it doesn't work with multiple GPUs.

Maybe all that is needed is to broadcast the result of the reduction from the boundary (MPI) processes, to the rest.

**Comment by kltrbrds** [comment]
Issue addressed with [#431](https://github.com/ammarhakim/gkylzero/pull/431)
