### ISSUE TITLE
[DR] sync corner cells over periodic boundaries

### ISSUE THREAD

**Issue by liangwang0734** [ammarhakim/gkylzero#399]
## Overview
- This DR aims to implement proper corner cell synchronization over periodic boundaries for the wave propagation method.
- A preliminary w.i.p.: https://github.com/liangwang0734/gkylzero/tree/sync_corners_periodic-prototype

## Background
- To allow source terms based on second-order derivatives, such as the gradient-based closure for the ten-moment model, or a simple isotropic/anisotropic diffusion/viscosity, diagonal corner ghost cells must be properly synhronized.
- Presently, the `sync_corners`  seem to handle interior (i.e. not on a logical boundary) ghost cells well. But this feature has not been implemented over periodic boundaries.
- With the `sync_corners`  enabled, `regression/rt_10m_burch_grad_closure.c` still do not give consistent results with different decompositions. For example, runs with `2x2` processors differ from a run with `1x1` processor.

### Three primary steps have been attempted in the prototype branch:
  - In `gkyl_rect_decomp_calc_periodic_neigh`, find neighboring ranks where the corner cells live
  - In `array_per_sync`,  communicate with all identified neighboring ranks
  - In `gkyl_mpi_comm_new`, enable `sync_corners`  in call to `gkyl_rect_decomp_calc_periodic_neigh`
```diff
------------------------------ zero/rect_decomp.c ------------------------------
index 539b24a3..a4160ef5 100644
@@ -253,8 +253,14 @@ gkyl_rect_decomp_calc_periodic_neigh(const struct gkyl_rect_decomp *decomp,
   const struct gkyl_range *curr = &decomp->ranges[nidx];
 
   int elo[GKYL_MAX_DIM] = { 0 }, eup[GKYL_MAX_DIM] = { 0 };
-  elo[dir] = eup[dir] = 1; // only extend in 1 direction
-  
+
+  if (inc_corners) {
+    for (int i=0; i<decomp->ndim; ++i)
+      elo[i] = eup[i] = 1;
+  } else {
+    elo[dir] = eup[dir] = 1; // only extend in 1 direction
+  }
+
```
```diff
------------------------------- zero/mpi_comm.c -------------------------------
index f94c734a..3e4b059b 100644
@@ -279,8 +279,8 @@ array_per_sync(struct gkyl_comm *comm, const struct gkyl_range *local,
         int delta[GKYL_MAX_DIM] = { 0 };
         delta[dir] = shift_sign[e]*gkyl_range_shape(&mpi->decomp->parent_range, dir);
 
-        if (mpi->per_neigh[dir]->num_neigh == 1) { // really should  be a loop
-          int nid = mpi->per_neigh[dir]->neigh[0];
+        for (int n=0; n<mpi->per_neigh[dir]->num_neigh; ++n) { // really should  be a loop
+          int nid = mpi->per_neigh[dir]->neigh[n];
 
           struct gkyl_range neigh_shift;
           gkyl_range_shift(&neigh_shift, &mpi->decomp->ranges[nid], delta);
@@ -315,8 +315,8 @@ array_per_sync(struct gkyl_comm *comm, const struct gkyl_range *local,
         int delta[GKYL_MAX_DIM] = { 0 };
         delta[dir] = shift_sign[e]*gkyl_range_shape(&mpi->decomp->parent_range, dir);
 
-        if (mpi->per_neigh[dir]->num_neigh == 1) { // really should  be a loop
-          int nid = mpi->per_neigh[dir]->neigh[0];
+        for (int n=0; n<mpi->per_neigh[dir]->num_neigh; ++n) { // really should  be a loop
+          int nid = mpi->per_neigh[dir]->neigh[n];
 
           struct gkyl_range neigh_shift, neigh_shift_ext;
           gkyl_range_shift(&neigh_shift, &mpi->decomp->ranges[nid], delta);
@@ -565,7 +565,7 @@ gkyl_mpi_comm_new(const struct gkyl_mpi_comm_inp *inp)
     mpi->neigh = gkyl_rect_decomp_calc_neigh(mpi->decomp, inp->sync_corners, rank);
     for (int d=0; d<mpi->decomp->ndim; ++d)
       mpi->per_neigh[d] =
-        gkyl_rect_decomp_calc_periodic_neigh(mpi->decomp, d, false, rank);
+        gkyl_rect_decomp_calc_periodic_neigh(mpi->decomp, d, inp->sync_corners, rank);
   
     gkyl_range_init(&mpi->dir_edge, 2, (int[]) { 0, 0 }, (int[]) { GKYL_MAX_DIM, 2 });
   
```
### Status of work
- With the above changes, the neighboring ranks seem to be properly located in tests with `1x2`, `2x1, `2x2`, and `3x3` processors, and the communicated data block size seem correct.
- But the results are still inorrect.
- Possible further fixes needed
  - I'm not sure if there are other steps to fully enable the corner syncronization over periodic boundaries.
  - I'm not sure if the simple fix can handle combination of periodic boundaries with wall boundaries correctly.

**Comment by ammarhakim** [comment]
This work is completed and there is no need for it. Periodic syncs already work in parallel, including 3D. Please see the gk-g0-app branch for the latest code in this regard. @kltrbrds has been using this now for > 2 months for doing 3D Bruch and LHDI with gradient-based closures.
