### ISSUE TITLE
[DR] cublasDgemm for modal/nodal conversions

### ISSUE THREAD

**Issue by johnson452** [ammarhakim/gkylzero#400]
My prototyping branch dg_10m_cublasDgemm_prototyping was branched from dg_10m, and I propose to merge this back into dg_10m.

(Similar changes implemented in gk-g0-app-GPU-Hack2024)

Description: 
Adds cu_mat_mm_array(...) to replace existing bottleneck in vlasov-lte-project when converting from nodal to modal quantities. This function calls the cublas function cublasDgemm(…) which performs a matrix multiplications which is approximately 2x faster in production cases for 2x2v can-pb calculations than unrolling the nodal to modal loops with maxima. 

This function, cu_mat_mm_array(...),  will reside in (new) mat_priv header with implementation in mat.c. It uses the cublas_v2 library function cublasv2Gemm(), which computes: alpha\*matrix_multiplication(A,B) + Beta*C = C.  This is particularly efficient since the matrix A is constant in time which converts nodal quantities, B, into modal quantities, C. B and C are gkyl_arrays and no reshaping of the data is required to perform these operations.

Requires:
Created new structure in gkyl_mat.h (implemented in mat.c), gkyl_phase_nodal_to_modal_mem, to store A, cublashandle, transpose, info, alpha, beta. This has been added to gkyl_vlasov_lte_proj_on_basis which uses this information in the gpu implemtation of lte-proj-on-basis to replace the phase modal to nodal calculation.   Structure is populated in Vlasov-proj-lte inew method for the specific nodal to modal phase-space calculation.

Other:
-	Removed exponential factor since it doesn’t matter.
-	Det_h and h_ij_inv calcs moved outside of the loops since they can be pre-computed.

Extra checklist:
[X] Does prototype PR Work? 
[X] Unit test passes: ?
[X] Regression test passes?
[X] Is memory freed?

**Comment by johnson452** [comment]
From our DR meeting (6/24/2024), the following changes were requested
- Move the cuda handles into gkyl_mat_mem structure
- With Openblas, make a CPU version of the matrix multiply, 
- Move the material from gkyl_mat_priv.h into gkyl_mat.h (which is enabled due to the first change - originally impossible because of having the cudahandle in the function sig.) Then remove gkyl_mat_priv.h and change the function signatures to gkyl_...

Further notes:
- The matrix is agnostic to the number of quadrature points and thus better for code maintainability

**Comment by JunoRavin** [comment]
I think this design is good and the initial testing is very promising. We should do a PR on this work as soon as @johnson452 feels ready for the code review.

**Comment by manauref** [comment]
Please clarify what you mean by "exponential factor"

**Comment by ammarhakim** [comment]
Completed and so we can close this DR.
