### ISSUE TITLE
[DR] Ionization model for low Te and charge exchange model

### ISSUE THREAD

**Issue by tnbernard** [ammarhakim/gkylzero#404]
The ionization model has been updated to allow for ionizations when the electron temperature is less than the ionization energy. A model of charge exchange based on [Bernard et al. PoP 2022](https://doi.org/10.1063/5.0087131) has also been added. These changes are included in https://github.com/ammarhakim/gkylzero/tree/gk-g0-app-neut. Conservation properties have been thoroughly tested and verified in simple and shaped tokamak geometries by @akashukla.

For ionization, the main file that is affected is apps/gk_species_react.c. Previously, the ionization term for electron species assuming that the primary and secondary electrons had the same average temperature: 

![Screenshot 2024-06-25 at 4 34 24 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/f5044b50-ac4b-41d3-96f2-0b8ae199cc1e)

Now we assume different temperatures for the primary and secondary electrons with a model that conserves energy: 

![Screenshot 2024-06-25 at 4 35 47 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/e367c811-a600-4eed-8f26-d8b152537833)

where ![Screenshot 2024-06-25 at 4 36 30 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/f77f9f38-9edf-4561-9ebf-d28d8110b52d) with

![Screenshot 2024-06-25 at 4 37 03 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/835d8eeb-d1e7-46f8-b30d-23462e5c7822) ,  
![Screenshot 2024-06-25 at 4 37 54 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/d43b0fca-3396-47d9-a04b-03c82be4add3). 

The charge exchange model includes changes to zero/dg_cx.c, zero/dg_cx_cu.cu, zero/gkyl_dg_cx.h, and zero/gkyl_dg_cx_priv.h. Kernels for calculating the reaction rate are contained in kernels/neutral/gkyl_dg_cx_kernels.h. The app was also edited in the files apps/gk_species_react.c and apps/gk_neut_species_react.c. 

The charge exchange collision operator is given by
![Screenshot 2024-06-25 at 4 45 22 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/b4a936c8-ac3d-4c45-83fd-e31117f69ca8)
with a relative velocity 
![Screenshot 2024-06-25 at 4 45 53 PM](https://github.com/ammarhakim/gkylzero/assets/11576466/dbf4dc16-8655-4527-81e2-307b5b83be38). 

The calculation of the relative velocity is done assuming Vlasov Cartesian components for the drift velocity u. That is, the u_parallel from GK species is projected onto the Vlasov components of the vector **u**. This is accomplished using the Cartesian components of the unit b vector which are stored as "bcart" the geometry object. ("bcart" is also used in the recombination collision term for projecting the ion maxwellian on the gk_neut_species grid.) The cross sections are modeled via fitting functions and currently only for hydrogen, deuterium, helium, and neon.

**Comment by JunoRavin** [comment]
@tnbernard do we have a succinct overleaf pdf explaining the derivation of the two temperatures in this low electron temperature model?

**Comment by tnbernard** [comment]
[Gkeyll_Low_Te_Ionization_Model.pdf](https://github.com/user-attachments/files/16351735/Gkeyll_Low_Te_Ionization_Model.pdf)

**Comment by JunoRavin** [comment]
Model implemented in PR https://github.com/ammarhakim/gkylzero/pull/430
