### ISSUE TITLE
[DR]: Multiblock syncs

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#413]
Here we propose a design for the cross-block sync in the (gyrokinetic) multiblock app.

The general idea is to follow the `sync` method in `zero/mpi_comm.c` (or `zero/nccl_comm.c`, though minor modifications are needed for GPUs). That is:
1. Post all the receives
2. Post all the sends.
3. Wait for the sends to end.
4. Wait for the receives to end and copy data from the receive buffer to the desired ghost range.

The details however are slightly different for MB sync. We comment on some below.

- Instead of looping over neighbors, we simply loop over conf-space dimensions and do the above operations once for the lower boundary, and once for the upper, if that boundary is not `GKYL_PHYSICAL`.
- We assume that blocks are conformal, i.e. the tangential plane at the boundary of two blocks is span by two identical ranges, one from either block.

1. To post the receives we need: a) a buffer of the right size to put the data into, and b) the rank we are receiving from. The former is easy: it’s just a buffer with the same size as the ghost range. The latter we obtain as follows:
- For a given boundary we know which block we need to communicate with (call it `neighb`).
- Loop over the ranks in `neighb` (the app already has this list).
- Check if this rank has the same tangential range as us. If it does, this is the rank we need to communicate e with.

2. A similar operation is performed to post the sends: enlarge the buffer so it’s as big as the appropriate skin range, copy the skin range into the buffer, send the buffer to the corresponding rank (identified using a procedure as the one described in the previous step).

3. The sends and receives above (isend/irecv) return a gkyl_comm_state. We can then wait for the sends using `gkyl_comm_state_wait`.

4. Similarly, wait for receives and use `gkyl_array_copy_from_buffer` to copy the data from the receive buffer to the ghost range of the distribution.

In pseudo-code, it would look like this
```
// Post receives
for bc=1,num_blocks_local {
  for dir=1,cdim {
    // Lower boundary
    If (lower_edge != GKYL_PHYSICAL) {
      recv_vol = lower_ghost[dir].volume * array->esznc
      if (buff_size(recv_buff[bc][dir].lower) < recv_vol) buff_resize((recv_buff[bc][dir].lower, recv_vol)

      // Loop over ranks in neighboring block & identify neighboring rank.
      neighb_rank = -1
      for i in neighb_ranks {
        if (gkyl_range_compare(&lower_ghost[dir], &neighb_skin_range)) {
          neighb_rank = neighb_ranks[i]
          break
        }
      }

      gkyl_comm_irecv(comm_multib, recv_buff[bc][dir].lower,
            recv_vol, GKYL_DOUBLE, neighb_rank, tag, recv_state[bc][dir].lower);
    }

    // Upper boundary
    If (upper_edge != GKYL_PHYSICAL) {
      recv_vol = upper_ghost[dir].volume * array->esznc
      if (buff_size(recv_buff[bc][dir].upper) < recv_vol) buff_resize((recv_buff[bc][dir].upper, recv_vol)

      // Loop over ranks in neighboring block & identify neighboring rank.
      neighb_rank = -1
      for i in neighb_ranks {
        if (gkyl_range_compare(&upper_ghost[dir], &neighb_skin_range)) {
          neighb_rank = neighb_ranks[i]
          break
        }
      }

      gkyl_comm_irecv(comm_multib, recv_buff[bc][dir].upper,
            recv_vol, GKYL_DOUBLE, neighb_rank, tag, recv_state[bc][dir].upper);
    }
  }
}

// Post the sends
(Pseudo code looks very similar to the above, except that were we used ghost ranges we use skin ranges, and vice versa, and instead of using recv buffers we use send buffers)

// Wait for the sends
for bc=1,num_blocks_local {
  for dir=1,cdim {
    // Lower boundary
    If (lower_edge != GKYL_PHYSICAL) {
      gkyl_comm_state_wait(comm_multib, send_state[bc][dir].lower)
    }

    // Upper boundary
    If (upper_edge != GKYL_PHYSICAL) {
      gkyl_comm_state_wait(comm_multib, send_state[bc][dir].upper) 
    }
  }
}

// Wait for receives and copy from buffer to distribution
for bc=1,num_blocks_local {
  for dir=1,cdim {
    // Lower boundary
    If (lower_edge != GKYL_PHYSICAL) {
      gkyl_comm_state_wait(comm_multib, recv_state[bc][dir].lower)
      gkyl_array_copy_from_buffer(f, recv_buff[bc][dir].lower, &lower_ghost[dir]);
    }

    // Upper boundary
    If (upper_edge != GKYL_PHYSICAL) {
      gkyl_comm_state_wait(comm_multib, recv_state[bc][dir].upper) 
      gkyl_array_copy_from_buffer(f, recv_buff[bc][dir].upper, &upper_ghost[dir]);
    }
  }
}
```

This procedure has been prototyped in the gk-g0-app_multib_sync branch. Some caveats:
- The code presently has a lot of repetition. I will modularize and make more compact after the DR.
- It uses isend/irecv, which may be undesirable. But thanks to the new gkyl_array_from_buffer_new method introduced in another branch, we can likely switch these to use array_isend/array_irecv.
- I haven’t tried to do it with GPUs, but I think a similar procedure will work. At least for the case that all blocks are on different GPUs. The only difference is that this procedure needs to take place inside a NCCL call group. If we have >1 block in one GPU, NCCL may not like it because this will be placing multiple comms to a single GPU before completing any of them; it may want us to do one at a time, but I don’t know for sure at this moment.
- Although this may work for MPI and NCCL, it may not work with null_comm as it’s currently prototyped because for null_comm isend/irecv won’t make sense. So, we can either package these, and other MB comms into an MB comm object, and have 3 versions of this (for null, mai, nccl), or we can write a separate multib_sync method for the null_comm case that is simpler and instead of using isend/irecv, it simply copies data to/from the appropriate places.

**Comment by ammarhakim** [comment]
This requires more discussion to align with the main MB DR. In particular, I would like to introduce a hierarchical comm object (perhaps, needs more thinking). Also, why do send and recv not make sense for `null_comm`? I mean send and recv are merely copies. We need to do this copy between block even in serial.

Also, connected with the main MB DR is:

- How to determine neighbors? This needs to be determined at app build time, of course.
- Mere send/recv is not enough as a coordinate transform needs to be applied also. How will it fit into the above scheme?

**Comment by ammarhakim** [comment]
I am closing this DR for now. This design is not what we would like to do as we should, if possible, hide raw send-recv methods inside some hierarchical comm. This also eliminates the leaking of the internal `gkyl_comm_state` that has crept into the comm IFCs. (The `gkyl_comm_state` is internal to MPI. Though this could be properly generalized to other communicators, it is not done at present).

After some thought and discussion I realize this is related to the refactoring of the comm system I would like to propose. In general, as my previous comment indicated, we need to have a hierarchical comm system, from lowest to highest, we need to have the following set of functions:

-  Functions that do not depend on decomp or block topology
- Functions that depend on a decomp but not a block-topology
- Function that depend on both decomp and block-topoloy

**Comment by manauref** [comment]
Reopening so we can have a discussion about the posted comments.

1. "This requires more discussion to align with the main MB DR": Sure, let's discuss. Keep in mind that this is a very targetted DR, for the sync specifically. Not the all comms, and not the required transformations, simply for sending/receiving f between blocks. Hence, this work, or an improved version of it, can be combined with other MB work happening elsewhere.
2. "why do send and recv not make sense for null_comm?" The specific set of sets described above, posting send and recv, I think don't work for a null comm. For a null comm what is needed are just copies, and that needs to know both the source data pointer and the destination data pointer, but send/recv only take one of these. So I think the multib_sync would have a different structure that doesn't do send/recv and simply copies.
3. "How to determine neighbors?" This is already done in this work. We know neighboring blocks, and we have a list of ranks per block. We simply find the rank in that neigboring block that shares the same perpendicular range as us.
4. "Mere send/recv is not enough as a coordinate transform needs to be applied also". Yes, this will happen as secondary transformation step. This DR is simply for the communication piece, and was submitted given that we were encouraged to do smaller, more frequent DRs.
5. "hide raw send-recv methods inside some hierarchical comm". Yes, we can do that. I can think about how to create a multib_comm object. But a question that I have, posted earlier, is whether we want 3 objects: multib_mpi_comm, multib_nccl_comm, multib_null_comm ?
6. "The gkyl_comm_state is internal to MPI": This isn't true, at least not as I understand the comment, because the NCCL comm also has a gkyl_comm_state, so the design proposed here I think would work with NCCL as well. For null_comm, as I said, I think we may need to just use copies instead of send/recv.
