### ISSUE TITLE
[DR] f-lte io and BGK Collision Restructuring

### ISSUE THREAD

**Issue by johnson452** [ammarhakim/gkylzero#414]
Design Review:
This was branched from dg_10m, and I propose to merge this new branch, dg_10m_f_lte_io-prototyping, back into dg_10m.

Description: 
This branch primarily does the following: 
-	Creates a new structure vm_lte, used within gkyl_vm_species to store moments/projection object/f_lte
-	Used in two places currently: (NEW) io of f_lte, and in the BGK collision routine to create f_lte.
-	New io flag (in the vm_species): output_f_lte 

Additions:
New file: vm_species_lte. This contains the functions: (no gkyl_... since they are private to vm)
```
// Initialize species lte object.
void vm_species_lte_init(…);

// Compute necessary moments for f-lte creation
void vm_species_lte_moms(…);

// Compute f-lte
void vm_species_lte(…);
```

With the new struct:
```
struct vm_lte {  
  struct gkyl_array *f_lte;

  struct vm_species_moment moms; // moments needed in the equilibrium

  // LTE distribution function projection object
  // also corrects the density of projected distribution function
  struct gkyl_vlasov_lte_proj_on_basis *proj_lte; 

  long self_niter; // total number of iterations correcting self collisions

  // Correction updater for insuring LTE distribution has desired LTE (n, V_drift, T/m) moments
  bool correct_all_moms; // boolean if we are correcting all the moments
  struct gkyl_vlasov_lte_correct *corr_lte; 
  gkyl_dynvec corr_stat;
  bool is_first_corr_status_write_call;
};
```

Tests:
- The regression test has been added: rt_can_pb_neut_bgk_sodshock_1x1v_p2, this outputs f_lte

Other Notes:
-	Moments for f_lte are now calculated inside the f. This is to guarantee the moments are always populated and updated before creating f_lte. (So I removed the moment calls before the bgk routines)
-	No longer accumulated for BGK since this is done by the f_lte: species_coll_mom_tm : 0

Extra checklist:
[X] Does prototype PR Work? 
[X] Unit test passes? (Checked ctest_canonical_pb_equilibrium  and ctest_corr_mj_integrated which are quite sensitive)
[X] Regression test passes?
[X] Is memory freed?

**Comment by JunoRavin** [comment]
I think we just call the iteration count niter instead of self_niter.

**Comment by johnson452** [comment]
> I think we just call the iteration count niter instead of self_niter.

We originally named it this way to differentiate with eventual cross collisions. I'm hoping this will be soon added! Do we still want to change this?

**Comment by JunoRavin** [comment]
I take your point, though this redesign does beg the question of how we should handle cross species collisions. It would be a lot more memory if you made another one of these objects for cross-species collisions, but would that be better? This object is nice and self-contained and it doesn't feel like it should know anything about cross-BGK moments. Or are you thinking cross-BGK will not use this object?
