### ISSUE TITLE
Pre-GPU Hack Cleanup: Eliminate specification of fluid_index in input file

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#44]
Because the fluid species struct and the kinetic species struct are separate objects which have to be looped over and we do not know _a priori_ how the user will order them, right now the input file has an extra layer of complication for introducing coupling between a fluid species and kinetic species. For example, inside the kinetic species struct the collisions struct looks like
`    .collisions = {
      .collision_id = GKYL_LBO_COLLISIONS,
      .ctx = &ctx,
      .self_nu = evalNuElc,
      .collide_with_fluid = "Pperp_elc",
      .fluid_index = 0,
    },    `

where fluid_index has to be consistent with the order you initialize the fluid species in. 

**Goal: eliminate this extra complication by getting both the index and the name of the species being collided with in the find_species methods**

**Comment by ammarhakim** [comment]
@JunoRavin Can this issue be closed? I think you fixed this?

**Comment by JunoRavin** [comment]
Issue solved as of https://github.com/ammarhakim/gkylzero/commit/5ef794665a78c51fe6b380e31316f0ab55aad9e2
