### ISSUE TITLE
[DR] Initializing a 5D distribution function from a 4D distribution in a file

### ISSUE THREAD

**Issue by Maxwell-Rosen** [ammarhakim/gkylzero#445]
MF 2024/09/12: I have completed a (serial) prototype of this. See my comment below.

For the mirror simulations, we aim to initiate a 3x2v gyrokinetic simulation using initial conditions derived from a 2x2v simulation. In the 2x2v setup, there is no dependence on the cylindrical angle. However, we aim to introduce this angular dependence in the 3x2v simulation by replicating the 2x2v data in each angular slice. Additionally, we would like to apply a user-specified function to this angular component to introduce noise into the initial conditions to trigger instabilities. These simulations should maintain consistent resolution and domain in velocity and physical space coordinates and use the same basis functions as the original data. Similarly, it would be valuable to load a 2x2v simulation from a 1x2v simulation of a single field line and then introduce radial dependence. Developing this infrastructure to initialize higher-dimensional simulations from lower-dimensional ones is crucial for advancing our mirror simulation efforts.

When loading this data, the structure in the code could look like this.
```
struct gkyl_gyrokinetic_species ion = {
   .projection = {
      .proj_id = GKYL_PROJ_FROM_LOWER_DIM,
      .filename = "ion_2x2v.gkyl"
      .func_dependence = user_func,
      .func_ctx = &ctx,
   },
};
```
The user may need to specify the original dimensions of the simulation, but I think that can be read from the file. I'm not sure what the projection routine would look like under the hood.

**Comment by Maxwell-Rosen** [comment]
I have gotten some initialization stuff working inside apps/gk_species_projection.c. I can load a lower-dimensional distribution function, read the grid, and construct lower-dimensional bases and ranges. I did not consider parallelism when creating these ranges and grids. The construction of these objects is identical to how gyrokinetic.c creates an app. It would re-use less code if we called gkyl_gyrokinetic_app_new() and created a new app with the appropriate dimensions instead. It would undoubtedly be less code, but this call has a lot of overhead, and it isn't a good idea.

The plan is to initialize inside the gk_proj object in gkyl_gyrokinetic_priv.h using the function gk_species_projection_init with the proj_id GKYL_PROJ_LOAD_LOWER_DIM. This structure will contain the lower dimensional grid, ranges, basis, and distribution function. I'm only interested in loading the 2x2v mirror distribution functions into a 3x2v simulation. Then, in gk_species_projection_calc, the code will call special kernels to map the 2x2v coefficients into the 3x2v spots and initialize the correct coefficients. I'm unsure how to create these kernels, but they should map one coefficient in each cell to another.

**Comment by manauref** [comment]
This work has been newly prototyped in the gk-g0-app_transdim branch.

The user can now specify another table (separate from `.projection`) like (e.g. for rt_gk_sheath_3x2v_p1):
```
ion = {
   ...
   .init_from_file = {
      .file_name = "gk_sheath_2x2v_p1-ion_1.gkyl",
    },
   ...
}
```
The code will then read the distribution from this file and proceed with the simulation. The infrastructure is intended to support:
1. Loading an f with the same grid as the current sim.
2. Loading an f with one dimensionality lower (e.g. 2x2v for a 3x2v sim).
3. Loading an f with the same dimensionality as the current sim, but a coarser grid (not yet implemented).
This is enabled by adding the function `gk_species_file_import_init` in apps/gk_species which does the file read, and translating the loaded f to the simulation IC, and by adding a new updater, `translate_dim_gyrokinetic`, which translates the DG coeffiients of a lower dim distribution to those of a higher dim distirbution.

**Comment by Maxwell-Rosen** [comment]
There are a few different options for `.type` that are available at the moment.

-  `GKYL_IC_IMPORT_NONE = 0,`
-  `GKYL_IC_IMPORT_F, // Import f only.` Imports the distribution function f from a lower dimensional simulation
-  `GKYL_IC_IMPORT_AF, // Import f and scale by alpha(x).` Scales F by alpha. alpha is the same function as conf_scale
-  `GKYL_IC_IMPORT_F_B, // Import f and add beta(x,v).` Beta is the same as `.phase_add`
-  `GKYL_IC_IMPORT_AF_B, // Import f, scale by alpha(x) and add beta(x,v).` Requires both `.conf_scale` and `.phase_add`

**Comment by manauref** [comment]
Done in PR #479
