### ISSUE TITLE
[DR] Cubic Representaion of Poloidal Flux for Magnetic Field Calculation

### ISSUE THREAD

**Issue by akashukla** [ammarhakim/gkylzero#448]
We can now use the cubic interpolator in dg_basis_ops.c to represent the poloidal flux, psi, read from EFIT files. Using a cubic representation of psi makes it easier to calculate the magnetic field since the second derivatives and cross derivatives are continuous. Previously, with our quadratic representation, we has to use recovery to achieve continuity in B.

Field line tracing can also be done using the cubics by passing use_cubics = true in the input file to the geometry grid input. However, it is extremely slow (200x slower for the STEP regression test)  at present and is not recommended.

The prototyping work has been done in this branch: https://github.com/ammarhakim/gkylzero/tree/multib-app_gk_cubicbmag . The changes made are:

1. Geometry methods which use EFIT now calculate B(R,Z) using the cubic representation
2.  There is an option to do field line tracing using the cubic representation using Gkeyll's builtin polynomial root finder. The X-point finder now uses this same option as it is important to be consistent.
3. functions to evaluate the second derivatives of the cubic interpolator were added to the cubic interpolator in dg_basis_ops.c

This change also makes it easy to calculate the magnetic field at R=0 using L'hopital's rule as

$$B_R = \lim_{R \to 0} \frac{1}{R} \frac{\partial \psi}{\partial Z}  = \lim_{R \to 0} \frac{\partial^2 \psi}{\partial Z \partial R},$$

$$B_Z = - \lim_{R \to 0} \frac{1}{R} \frac{\partial \psi}{\partial R} = - \lim_{R \to 0} \frac{\partial^2 \psi}{\partial R^2}.$$

Tests demonstrate that we can go to R= 0 using this method. 

Note: Our old method had a consistency issue: psi(R,Z) used for field line tracing was different than the recovered psi(R,Z) used for magnetic field calculation. Our new method when used as recommended (cubics for magnetic field calculation, and quadratics for field line tracing), has the same consistency issue.  Using the cubics for the field line tracing as well would resolve the consistency issue, but this will be impractical until the root finders are sped up.

**Comment by akashukla** [comment]
Here are some plots of the wham grid and magnetic field : Tracing using quadratics and field using cubics.
![wham_to_axis_bmag](https://github.com/user-attachments/assets/9c869a4b-ad15-4d3c-83ed-6130876b9e97)
![wham_to_axis](https://github.com/user-attachments/assets/0fb58193-50aa-4f2c-ac54-62ef80d41e06)

**Comment by akashukla** [comment]
I have only one good example of cubics used for tracing. This test does not cover the X-point or R=0, since those grids typically take longer to trace. Here I am showing a small STEP far SOL grid traced using the cubics (orange) and quadratics (blue). They are mostly the same, but in the zoomed in  plot you can see slight differences in the node locations. This took 27 seconds using quadratics for tracing and 4600 seconds using the cubics.

![step_cubic_quad_trace_zoomed](https://github.com/user-attachments/assets/0d23e724-cc7f-4151-bf35-f6dd7ee1a370)
![step_cubic_quad_trace](https://github.com/user-attachments/assets/3f91d07c-d290-4b54-81a5-7c9389aae185)

**Comment by akashukla** [comment]
Here is an example STEP grid and Field which touches the X-point. It uses quadratics for tracing and cubics for the field. This is from the regression test.
![step_quad_xpt](https://github.com/user-attachments/assets/929b6134-d912-44d7-93c8-eb6f6c372327)

**Comment by JunoRavin** [comment]
Issue address with https://github.com/ammarhakim/gkylzero/pull/463
