### ISSUE TITLE
[DR] Specifying a varying minimum temperature for the radiation

### ISSUE THREAD

**Issue by jRoeltgen** [ammarhakim/gkylzero#451]
At relatively low temperatures, the emissivity can go negative. Since different element and charge states stop radiating at different temperatures (e.g. Ar+17 has little to no radiation below 100eV, but every neutral species radiates down to single digit electron temperatures) it was unclear at first how a minimum temperature should be implemented. 
I found though that "the temperature at which the species stops radiating" is almost entirely dependent on the V0 fitting parameter shown in the below figure. 
![te_cutoff_vs_v0_factor4](https://github.com/user-attachments/assets/2efa10e2-7c8c-460e-8db3-801c0ce3c92f)
"The temperature at which a species stops radiating" is measured by what temperature the emissivity falls below some percentage of the maximum emissivity. A conservative estimate for this, currently used as the default, is about 0.3% of the maximum emissivity which led to no instances of negative emissivity in the tests run. A more aggressive option of 0.01% is also available, which led to a small temperature range of negative emissivities.

The prototyping branch is: https://github.com/ammarhakim/gkylzero/tree/gk-g0-app-emissivity_pos_fix

**Comment by tnbernard** [comment]
This appears to be a robust method to prevent negative emissivity. Can you describe in your design review how, if at all, the input files change? Is this fix automatically applied with a default tolerance? How does the user specify or change the tolerance? Examples would be helpful here.

**Comment by jRoeltgen** [comment]
@tnbernard The default option would require no change in the input file, see regression/rt_gk_rad_nonuniformv_1x2v_p1.c:
`.radiation = {
      .radiation_id = GKYL_GK_RADIATION, 
      .num_cross_collisions = 1,
      .collide_with = { "ion" },
      .z = 1,
      .charge_state = 0,
      .num_of_densities = 1, 
                                                                                                                       
    },
`
To specify a constant temperature or a lower variable temperature the te_min enum and T_min_eV variables are added to the input file (regression/rt_gk_rad_1x2v_p1.c):

`  .radiation = {
      .radiation_id = GKYL_GK_RADIATION,
      .num_cross_collisions = 1,
      .collide_with = { "ion" },
      .z = 1,
      .charge_state = 0,
      .num_of_densities = 1,                                                                                                                      
      .te_min = GKYL_CONST_TE,
      .T_min_eV = 12.0,

    },

The options for the te_min enum are:

- GKYL_CONST_TE (a constant temperature for every fit specified in T_min_eV)
- GKYL_VARY_TE_CONSERVATIVE (default, the te_min using 0.3% as the plot above)
- GKYL_VARY_TE_AGGRESIVE (the te_min uses 0.01% of the maximum emissivity to find the minimum temperature)

`

**Comment by manauref** [comment]
Addressed in PR #495
