### ISSUE TITLE
[DR] Upgrade positivity shift to maintain quasineutrality

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#453]
Presently we have an updater, `positivity_shift_gyrokinetic`, which is meant to enforce positivity of the distribution function `f` at certain "check" points (presently Gauss-Legendre quad points, but could be changed to Gauss-Lobatto nodes) . It works as follows:

1. Loop over phase space.
2. In each cell, perform a modal-2-nodal transform & check if $f_{\mathrm{in}}<0$ at check points.
3. If $f_{\mathrm{in}}$ is <0 at a check point, raise $f_{\mathrm{in}}$ to 0 at that point.
4. Perform a nodal-2-modal transform of the distribution $\Rightarrow f_{\mathrm{shifted}}$.
5. If a shift was performed, compute $\Delta  f=f_{\mathrm{shifted}} - f_{\mathrm{in}}$.
6. Compute and output the integrated moments of $\Delta  f$.

This is done independently to each species. As one would expect, this may not preserve quasineutrality in gyrokinetics as one may add electrons but not ions, or viceversa.

We propose to modify this updater so it preserves quasineutrality as follows:
1. Use a two-loop structure, one over conf- and one over vel-space, like we do in computing moments.
2. In the conf-loop, check if the current M0 moment (guiding center density $n_s$) if >0.
3. In the vel-loop, shift `f` if needed (as described above).
4. If M0 was >0 in this conf-cell, re-scale `f` so it has the same M0 as before the shifting. This procedure alone would guarantee (guiding-center) quasineutrality, because the number densities where not changed.
5. If M0 was <0 somewhere, we will have added some (guiding-center) density. After the above procedure is done to each species compute $\Delta  n_s=n_{s,\mathrm{shifted}} - n_{s,\mathrm{in}}$ and rescale each species species as
$$f_{s,\mathrm{new}} = \left[\left(n_{s,\mathrm{shifted}}+h_{sr}\right)/n_{s,\mathrm{shifted}}\right] f_{s,\mathrm{shifted}}$$
where
$$h_{sr}= \max(0, (\Delta n_r^{(0)} - \Delta n_s^{(0)})/|\Delta n_r^{(0)}-\Delta n_s^{(0)}|) * (\Delta n_r-\Delta n_s)$$
Because we are using the cell-average ($\Delta n_r^{(0)}$) to determine whether to scale a species or not, this will only guarantee to preserve quasineutrality in the cell average. It's harder to enforce quasineutrality everywhere within the cell, so we'll start with this.

The last step is a little more complicated when there are multiple ion species. In that case will compute the total ion density shift $\Delta  n_{\mathrm{ions}}=\sum_{s | q_s>0}\Delta  n_s$ and we compute the electron $h$ scaling factor as
$$h_{e,\mathrm{ions}}= \max(0, (\Delta n_{\mathrm{ions}}^{(0)} - \Delta n_e^{(0)})/|\Delta n_{\mathrm{ions}}^{(0)}-\Delta n_e^{(0)}|) * (\Delta n_{\mathrm{ions}}-\Delta n_e)$$
while for each ion the $h$ scaling factor will be
$$h_{ie}= \max(0, (\Delta n_e^{(0)} - \Delta n_{\mathrm{ions}}^{(0)})/|\Delta n_e^{(0)}-\Delta n_{\mathrm{ions}}^{(0)}|) * (\Delta n_e-\Delta n_{\mathrm{ions}}) * \left(\Delta n_i/\Delta n_{\mathrm{ions}}\right)$$

The positivity shift updater can later be changed to apply a Moe–Rossmanith–Seal limiter instead.

@gwhammett may want to read this

**Comment by ammarhakim** [comment]
This looks reasonable. We should produce an implementation of this modified updater so we can test with the simulations Dingyun is doing.

**Comment by manauref** [comment]
Just pushed a version of this to the gk-g0-app_pos_shift_mod branch

**Comment by manauref** [comment]
I've been doing some more testing and analysis of this modified positivity shift. Here's an example of how it's behaving in our `rt_gk_sheath_3x2v_p1` regression test.

After a single step the total guiding-center charge density is the same as if we had not enforced positivity:
<img width="967" alt="Screenshot 2024-09-10 at 10 09 05 AM" src="https://github.com/user-attachments/assets/04864404-182a-4de6-8dde-b508b2435bcc">

If you run the test fully (649 steps to 6 micro sec), we still see a similar behavior (i.e. guiding center charge density is unaffected):
<img width="790" alt="Screenshot 2024-09-10 at 10 12 45 AM" src="https://github.com/user-attachments/assets/2a3ccfe3-c521-41ba-8d8c-53df73f82314">

Did the positivity shift do anything? Yes; here's the difference between the integrated moments ($M_0$, $M_1$, $M_{2\parallel}$, $M_{2\perp}$) of the electrons in the simulation with positivity and the simulation without:
<img width="1312" alt="Screenshot 2024-09-10 at 10 25 07 AM" src="https://github.com/user-attachments/assets/28ad9508-b413-40ad-8b61-40ce2fbe6cc6">
This may seem like a plot of how much stuff we added (or subtracted), but it's not actually that. Notice that in most of the simulation it seems to indicate that the number of particles (c0) is larger when running with positivity. My speculation is that in the early times of this (very coarse and short) simulation, we added particles (and possibly momentum/energy)
<img width="752" alt="Screenshot 2024-09-10 at 10 31 02 AM" src="https://github.com/user-attachments/assets/350e850c-69ee-490c-9174-f4e0c32fc5f1">
(notice the time window) and this changed the course of the simulation later on, leading to different fluxes out of the simulation and thus different particle, momentum, energy contents.

To see how much stuff we actually added, we can compare the moments of the positivity shift to the moments of f. Here are these two for the electrons
<img width="1275" alt="Screenshot 2024-09-10 at 10 58 19 AM" src="https://github.com/user-attachments/assets/1f0a8b90-baa2-4d82-be8e-7be9db97b5ae">
What we see here (top row is integrated moments of f, bottom row is integrated moments of the positivity shift):
- c0: Almost no particles are added
- c1: Transiently there may be O(0.1%) momentum added.
- c2: O(0.01%) parallel kinetic energy is added.
- c3: O(0.001%) perpendicular kinetic energy is added.
These numbers may look great, but of course, this is a coarse test, run for little time, with no turbulence or steep profiles. These percentages will surely increase considerably in production sims. The notable thing to notice here is that the number of particles added is down to machine precision, preserving quasineutrality.

**Comment by manauref** [comment]
Addressed in PR #461
