### ISSUE TITLE
Same comments for different parameters in gkyl_tok_geo.h

### ISSUE THREAD

**Issue by dingyunl** [ammarhakim/gkylzero#455]
https://github.com/ammarhakim/gkylzero/blob/25336311103fbff6951f1188e77be3b88935b56a/zero/gkyl_tok_geo.h#L137 

@akashukla These three lines have the same comment. Could you please correct them?

**Comment by JunoRavin** [comment]
Issue addressed with https://github.com/ammarhakim/gkylzero/pull/467
