### ISSUE TITLE
Add input file flag to set frequency that distf is written out for (gyro)kinetic species

### ISSUE THREAD

**Issue by tnbernard** [ammarhakim/gkylzero#478]
Currently distribution functions are written out at every frame. This takes up a large amount of disk space. It would be useful to set a frequency relative to the num_frames, like distf_freq = 0.1. If you have a flag to set the total number of distf frames output, as we did in g2, you have to remember to update it if you extend t_end and output frames, whereas with a frequency it will happen automatically.

**Comment by manauref** [comment]
Addressed in PR #484
