### ISSUE TITLE
Add X-point Finder for Serendipity basis

### ISSUE THREAD

**Issue by akashukla** [ammarhakim/gkylzero#480]
Serendipity basis representation of Psi(R,Z) is generally supported for single block mirror or tokamak simulations. However, in simulations that require the x-point location (for example multiblock tokamak simulations), using serendipity basis for psi(R,Z) will cause an error - the x-point finder only works for tensor basis. I need to either remove serendipity basis entirely or make the x-point finder work for serendipity basis.

**Comment by JunoRavin** [comment]
My immediate thought is that Serendipity isn't going to help much in this circumstance because the Serendipity basis only decreases the number of basis functions in 2D from 9->8 for p=2 and 16->12 for p=3. Most of the benefit in Serendipity is higher dimensional simulations.

**Comment by akashukla** [comment]
Solved in PR #481
