### ISSUE TITLE
Positivity fix and Boltzmann Electrons

### ISSUE THREAD

**Issue by Maxwell-Rosen** [ammarhakim/gkylzero#494]
The positivity fix does not work with Boltzmann Electrons at the moment. There is an issue with the quazineutrality update

`
Thread 1 "sim" received signal SIGSEGV, Segmentation fault.
0x0000155547628f48 in gkyl_positivity_shift_gyrokinetic_quasineutrality_scale_cu(gkyl_positivity_shift_gyrokinetic *, const gkyl_range *, const gkyl_range *, const gkyl_array * __restrict__, const gkyl_array * __restrict__, const gkyl_array * __restrict__, const gkyl_array * __restrict__, gkyl_array * __restrict__) (up=0x1e52f670, conf_rng=0x15079e8, phase_rng=0x1829aa40, delta_m0s=0x1e52c950, delta_m0s_tot=0x1e539630, delta_m0r=0x7900, m0s=0x17a613d0, fs=0x17a673e0) at zero/positivity_shift_gyrokinetic_cu.cu:304
304	  gkyl_positivity_shift_gyrokinetic_quasineutrily_scale_cu_ker<<<nblocks, nthreads>>>(
(cuda-gdb) bt
#0  0x0000155547628f48 in gkyl_positivity_shift_gyrokinetic_quasineutrality_scale_cu(gkyl_positivity_shift_gyrokinetic *, const gkyl_range *, const gkyl_range *, const gkyl_array * __restrict__, const gkyl_array * __restrict__, const gkyl_array * __restrict__, const gkyl_array * __restrict__, gkyl_array * __restrict__) (up=0x1e52f670, conf_rng=0x15079e8, phase_rng=0x1829aa40, 
    delta_m0s=0x1e52c950, delta_m0s_tot=0x1e539630, delta_m0r=0x7900, m0s=0x17a613d0, 
    fs=0x17a673e0) at zero/positivity_shift_gyrokinetic_cu.cu:304
#1  0x0000155542a95b1b in gkyl_positivity_shift_gyrokinetic_quasineutrality_scale (
    up=0x1e52f670, conf_rng=conf_rng@entry=0x15079e8, phase_rng=0x1829aa40, 
    delta_m0s=0x1e52c950, delta_m0s_tot=0x1e539630, delta_m0r=0x7900, m0s=0x17a613d0, 
    fs=0x17a673e0) at zero/positivity_shift_gyrokinetic.c:157
#2  0x0000155542bb8a82 in rk3 (dt0=<optimized out>, app=0x1507850) at apps/gyrokinetic.c:2309
#3  gkyl_gyrokinetic_update (app=app@entry=0x1507850, dt=dt@entry=0.00050000000000000001)
    at apps/gyrokinetic.c:2344
#4  0x00000000004024a8 in main (argc=<optimized out>, argv=<optimized out>) at sim.c:787`

**Comment by manauref** [comment]
Fixed in PR #502
