### ISSUE TITLE
Porting of the flipSign method from G2 into G0

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#5]
Some boundary conditions (Maxwell's conducting wall and symmetry boundary condition, Vlasov reflecting wall) make use of the basis.flipSign method to flip the sign of every odd basis function (odd powers in the basis function variables). This method should be ported to G0, but we should re-visit the structure of this method, which is currently a method within Basis.lua. This structure makes some amount of sense as the method is only called as a function to give how the components in the ghost cell depend on the components in the skin cell (so similar to other BC functions). 

I do not think this method is used anywhere else besides boundary conditions though, and one can imagine instead making a method with rect_apply_bc that does this operation to a DG field instead of making it a method of cart_modal_serendip (on the same level as the eval_basis method).

**Comment by manauref** [comment]
If one is only using flipSign, this makes sense.

What about the case where flipSign is just a step of a more complicated BC?

**Comment by ammarhakim** [comment]
These methods should go into the kernel/basis directory. These are just simple functions and should go in that directory. Then, they should be hooked into the gkyl_basis struct in the same manner as the eval method is hooked in.

**Comment by ammarhakim** [comment]
Can someone explain to me how the flipSign method works? For example, I see in one of the functions:

```
_M[2] = function (dir, f, out) 
   if dir == 1  then 
   out[1] = f[1] 
   out[2] = -1.0*f[2] 
   out[3] = f[3] 
   end 
end 
```

There is no else clause to this method! So what happens with dir is not 1? This is repeated in every single place. How can this be correct?

**Comment by manauref** [comment]
Was there a response to this?

**Comment by JunoRavin** [comment]
I have messaged Ammar and am coordinating with him.

**Comment by ammarhakim** [comment]
I completed the generation of flip_sign method. Closing this issue, though this method needs to be hooked into the main basis struct.

**Comment by manauref** [comment]
what was the response to Ammar's question though? others might want to learn

**Comment by ammarhakim** [comment]
To answer my question: JJ actually never responded to me :) However, the question was a stupid one! The else clause did not exist only in 1D as dir can only be 0. Else clause exist in all other NDIM>1.
