### ISSUE TITLE
Pre-GPU Hack Cleanup: Complete hook-in of proj_maxwellian_on_basis and porting to GPUs

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#50]
proj_maxwellian_on_basis from lab moments (M0, M1i, and M2) is completed and tested on the CPU. Need to:
1. Complete and test proj_maxwellian_on_basis from plasma frame moments (n, u, T)
2. Hook-in proj_maxwellian_on_basis to app as a means of specifying the initial conditions (this hook-in will also serve as an example of how to deploy proj_maxwellian_on_basis for other parts of the code such as BGK collisions and neutral interactions)
3. Port proj_maxwellian_on_basis to GPUs. 
4. Extend proj_maxwellian_on_basis to special relativity and create proj_maxwell_juttner_on_basis. Note: this requires special functions and is only (reasonably) defined in one momentum dimension and three momentum dimensions (fractional MacDonald functions are possible but to my knowledge are not implemented in standard math libraries and likely not worth the trouble here).

**Comment by JunoRavin** [comment]
This functionality has existed in at least some form for awhile, but I am officially closing this issue especially now with the recent PR: https://github.com/ammarhakim/gkylzero/pull/328

that unifies the relativistic and non-relativistic "Maxwellian" (or in a more formally correct parlance the local thermodynamic equilibrium, LTE) distribution projection on CPUs and GPUs.

**Comment by manauref** [comment]
@manauref I thought I showed that projection at Gauss-Lobatto nodes is not the same as eval_on_nodes.
