### ISSUE TITLE
[DR] Modify collisionless GK discretization to guarantee L2 norm conservation/decay

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#551]
Motivation
-----------

This DR intends to address a long-standing issue with the GK discretization in curvilinear coordinates dating back to g2 and still present in g0. We will refer to equations in the following document
[GkeyllGKalgo-new_20241205.pdf](https://github.com/user-attachments/files/18029453/GkeyllGKalgo-new_20241205.pdf)
which is a modified version of one I shared on Dec 2. That one contained the algorithm presently in the code, this new one contains what we propose to do here.

We evolve a kinetic equation for F = J_x B f = J_T f (equation 49, but we disregard the velocity mapping in this DR) like
dF/dt + d/dx^i \dot{x^i} F + d/dvpar dot{vpar} F = 0
as in equation 51.

If one works through the L2 norm conservation (decay) with central (upwind) fluxes for the discrete scheme we currently have in Gkeyll, we see that contributions that should cancel at cell surfaces when we add over all cells (equation 123) do not actually cancel. This is because weak multiplication of J_x B f to produce F gives different values of
`f_j(x=1)*F_{j+1}(x=-1)`
and
`f_{j+1}(x=-1)*F_j(x=1)`
However this is not a problem if we use a slightly different scheme where the surface term is written as
```
int dS_i psi_k J_x B \dot{x^i} hat{f} |_{x^i=+/- 1}
```
as in equation 52. This still conserves particles and energy (provided J_x B \dot{x^i} is computed in a continuous way), and a consequence of writing it like this way is that the two contributions in the L2 norm conservation mentioned above cancel each other, such the the L2 norm of f is conserved with central fluxes (equations 123-124).

I believe @johnson452 @akashukla and I semi-independently (with some communication) worked through these or similar equations concurrently (the former doing it for the canonical Poisson-Bracket Vlasov system).

Proposed changes
-------------------

The necessary changes are rather minimal I think.
1. We will modify `dg_calc_gyrokinetic_vars_alpha_surf` so that instead of computing \dot{x^i} it computes J_x*B*\dot{x^i} at surfaces.
2. We will modify the volume term of the collisionless GK part so that it interprets the input distribution as f instead of J_Tf. This means we will also insert a factor of J_T (`jacobTot`) in the volume terms now.
3. We will divide `jacobTot` out of J_Tf right before computing the collisionless terms in line 717 of apps/gk_species.c:
https://github.com/ammarhakim/gkylzero/blob/54de637b3aa5f665c5345742be321067863e2e54/apps/gk_species.c#L717
storing the result in a new array, say `finDJtot` for `fin` divided `D` by `jacobTot` (Jtot). We don't actually have a conf-phase weak division in Gkeyll, so we will instead multiply by 1/J, which is equivalent for $p=1$.

We will prototype potential solutions in the `gk-g0-app_l2mod_prototype` branch.

Pros and cons
--------------

There are a couple of pros and cons in the above proposal to consider:
- Pro: dividing J_T out for both surface and volume terms spares us changes to hyper_dg, which would otherwise have to take 2 distributions and pass each to volume and surface terms
- Con: storing the division of J_Tf / J_T in a separate array means allocating yet another distribution, at a time when we are already short on GPU memory. We can do this to test at first, but should consider other options like: a) is it safe to temporarily use another distribution allocated for RK stages? b) hyper_dg applies the volume term first, we could modify hyper_dg (or create a new version of it) so it does the division in a single phase-space cell before applying the volume term, and stores them in a local array (of size num_basis); it'd have to do it for its neighbors too to be used in the surface terms, and shift the values over as it steps through the grid so we don't recompute these divisions.

Something curious
-------------------

We didn't discuss the velocity space Jacobian, J_v, in this DR. But it is included in the above PDF. Curiously it doesn't seem necessary to divide J_v out of J_Tf to conserve particles, energy, or L2 norm. Its curious, strange and suspicious that the v-space Jacobian would be on a different footing than the curvilinear and gyrocenter coordinate Jacobians. A second look at this is advised.

**Comment by JunoRavin** [comment]
Just as an initial comment, this issue about the velocity-space Jacobian is wrong. You can get the same lack of L2 conservation from utilizing central fluxes (or decay with upwind fluxes) from the vparallel advection if the velocity space Jacobian has a basis expansion. We need to make these adjustments because of the fact that (J f)_h =/= J_h f_h if the Jacobian has an expansion.

**Comment by manauref** [comment]
We don't have a Jacobian with an expansion in GK. But that explains it.
Thanks @junoravin

**Comment by ammarhakim** [comment]
This DR needs to be closed. As discussed in the meeting of December 11th 2024 there is no way to to L2 in the general case when J is not a constant. This is not very carefully explained in an upcoming paper by Grant & myself.
