### ISSUE TITLE
Fix incorrect memory access in vm_species_source

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#68]
rt_sheath_1v doesn't not run on GPUs on Stellar due to an incorrect memory access. It runs on Traverse but I believe that's serendipitous because Traverse does a host-device copy under the hood, presumably facilitated by the NVlink or some other hardware difference (which we in general should not count on).

I believe the problem lines in the reductions in lines 47 and 49 of apps/vm_species_sources:

```
    for (int d=0; d<app->cdim; ++d) {
      gkyl_array_reduce(red_mom, src->source_species->bflux.integ_moms[2*d].marr, GKYL_SUM);
      src->scale_factor += red_mom[0];
      gkyl_array_reduce(red_mom, src->source_species->bflux.integ_moms[2*d+1].marr, GKYL_SUM);
      src->scale_factor += red_mom[0];
    }
```

They are putting the result of the reduction on a host array, but when run on GPUs the result should be placed in a device array (an check how they are used subsequently). See unit/ctest_array_reduce.

**Comment by kltrbrds** [comment]
Latest commit fixes this, rt_sheath_1v now runs on Stellar GPUs.
