### ISSUE TITLE
BinOp questions

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkylzero#7]
I am trying to understand the signature of the binOp methods in G2 kernels. For example, I see:

```
void CartFieldBinOpMultiply1xSer_P2(binOpData_t* data, const double *A, const double *B, const short int Ncomp, const short int eqNcomp, double *out) 
```

What do args `Ncomp` `eqNcomp` accomplish? Is this to allow multiplying say a sub-set of components? Is this facility used anywhere and should we retain it (in some form or the other)?

Also, I see the arg `binOpData_t* data'. I see it used for example:

```
data->AEM_S = Eigen::MatrixXd::Zero(3,3); 
```

It seems to me this defeats the purpose of having data, right? I mean, this call will create a new matrix of 3x3 and copy it to the `data->AEM_S`. Hence, the original contents will be deleted, new copy made and copied into the variable. So it is even more expensive than creating the matrix in-line! So why even have a data if again and again in each cell in each step we alloc/dealloc matrices etc?

**Comment by manauref** [comment]
*eqNcomp* is used to differentiate between vector-vector and scalar-vector
multiplication. The former was used for a diagnostic that computed kinetic
energy direction-wise, but is no longer used I think. Kolter is dropping it.

*nComp* is used to tell the kernel how many vector components there are
(e.g. 2 for a 2v M1i), to perform operations component-wise.

*Eigen::MatrixXd:Zero(3,3):* I looked at that a couple of days ago and was
under the impression that that is simply calling the zero-out function in
the Eigen::MatrixXd class, not actually creating a new function.
But you may be right, and it's creating a new matrix. I just did a quick
search and found that static matrices like the ones we are using have
a setZero()
method
<https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#af230a143de50695d2d1fae93db7e4dcb>.
So this perhaps should be replaced by *data->AEM_S.setZero()*

**Comment by ammarhakim** [comment]
When you say "perform operations component-wise" do you mean multiplying two DG vector fields together, for example?

Before any new kernels are generated, please talk to me. As I said last week, I will do the multiply kernels myself (done already). At this point I believe the more important thing is to design the multi-species collisions properly and not worry about the binops per-se. I will set the code structure over the next few days for this and then divisions can be implemented. More importantly for now:

Please list the precise set of bin-ops needed in collisions. So, for example, scalar-scalar multiply, vec-vec multiply etc etc. That will allow us to make sure these ops are ready.

**Comment by manauref** [comment]
I mean multiply *u*u* where *u* is a vector, so that in 2v the result is a
vector field with [u_x^2, u_y^2].

Conf-space operations needed are
- scalar * scalar
- scalar * vector
- scalar / scalar
- vector / scalar
- vector . vector
 Phase space operations needed:
- conf scalar * phase scalar

vector*vector component wise is not needed (for now).

**Comment by ammarhakim** [comment]
I am proposing to reorg the bin_op kernels in the following way. The kernel signature will be changed to (for example)

```
void binop_mul_1d_ser_p0(const double *f, int fstart, const double *g, int gstart, double *fg, int fgstart )
```

The `fstart` `gstart` and `fgstart` will indicate the starting point in the respective arrays. So scalar-scalar multiply to copy into a scalar file would look like:

```
binop_mul_1d_ser_p0(f, 0, g, 0, fg, 0);
```

Scalar-vector multiply would need a loop:

```
for (int d=0; d<NDIM; ++d)
  binop_mul_1d_ser_p0(f, 0, g, d, fg, d);
```

where `f` is a scalar field and `g` and `fg` are vector fields. This would basically scale every vector component by f.

This is considerably more flexible than at present as it allows essentially arbitrary combinations of ops by calling things in a loop with the appropriate start index.

Let me know if this is an issue or if there are other suggestions.

**Comment by ammarhakim** [comment]
Actually, now that I think of this: there is really no need for any such extra start indices. The code that calls the kernels can increment the pointer appropriately as it wants. The kernel should assume that only a `nbasis` length array is passed to it, leaving to the caller to ensure proper pointer arithmetic has been done to access the appropriate vector/scalar as needed, and also add the loops as needed.

**Comment by manauref** [comment]
Presumably pointer arithmetic doesn't cost anything. So this seems fine.

**Comment by ammarhakim** [comment]
This is now resolved. I fixed the bin_op signatures to be like array_ops without the need for an updater. This allows using the ops in a more flexible manner. All combinations of scalar*scalar, scalar*vector etc are supported.
